marvel:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: ${{ secrets.DB_HOST }}
      port: ${{ secrets.DB_PORT }}
      user: ${{ secrets.DB_USER }}
      pass: ${{ secrets.DB_PASS }}
      dbname: ${{ secrets.DB_NAME }}
      schema: staging

    prod:
      type: postgres
      threads: 1
      host: ${{ secrets.DB_HOST }}
      port: ${{ secrets.DB_PORT }}
      user: postgres 
      pass: ${{ secrets.DB_PASS }}
      dbname: ${{ secrets.DB_NAME }}
      schema: production

  target: dev
