marvel:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: marvel-db-instance.costxf40yxh2.us-east-1.rds.amazonaws.com
      port: 5432
      user: postgres 
      pass: Awesome2023
      dbname: marvel_db
      schema: staging

    prod:
      type: postgres
      threads: 1
      host: marvel-db-instance.costxf40yxh2.us-east-1.rds.amazonaws.com
      port: 5432
      user: postgres 
      pass: Awesome2023
      dbname: marvel_db
      schema: production

  target: dev

 DB_HOST: 
  DB_PORT: 
  DB_USER: 
  DB_PASS: 
  DB_NAME: