name: dbt CI workflow

# define events
on:
  push:
    branches: ['main']

# define the ci job
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'

      - name:  Install dbt dependencies
        run: |
          pip install dbt-core
          pip install dbt-postgres
          dbt deps

      - name: Run dbt models
        run: dbt run --profiles-dir . --target c

      - name: Build dbt docs
        run: dbt docs generate --profiles-dir . --target c

      - name: Prepare docs for publishing
        run: |
          mkdir -p public
          mv target/* public/

      - name: Build dbt models
        run: dbt build --profiles-dir . --target c



