services:
  marvel:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - marvel_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      - MB_DB_TYPE=${MB_DB_TYPE}
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_PORT=${MB_DB_PORT}
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_HOST=${MB_DB_HOST}
    ports:
      - "3000:3000"
    depends_on:
      - marvel

volumes:
  marvel_data:

# pgcli -h localhost -p 5432 -U root -d marvel_db