name: dbt CI workflow

# define events
on:
  push:
    branches: ['main']

# define the ci job
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'

      - name:  Install dbt dependencies
        working-directory: ./dbt
        run: |
          pip install dbt-core
          pip install dbt-postgres

      - name: Run dbt models
        working-directory: ./dbt
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run --target prod --profiles-dir ." 
        
        # define set variable
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}

      

      - name: Build dbt models
        working-directory: ./dbt
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt build --target prod --profiles-dir ." 
        
        # define set variable
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}