name: dbt CI workflow

# define events
on:
  push:
    branches: ['main']

# define set variable
env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}

# define the ci job
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'

      - name:  Install dbt dependencies
        working-directory: ./dbt
        run: |
          pip install dbt-core
          pip install dbt-postgres

      - name: Run dbt models
        working-directory: ./dbt
        run: dbt run --profiles-dir . --target prod

      - name: Build dbt docs
        working-directory: ./dbt
        run: dbt docs generate --profiles-dir . --target prod

      - name: Prepare docs for publishing
        working-directory: ./dbt
        run: |
          mkdir -p public
          mv target/* public/

      - name: Build dbt models
        working-directory: ./dbt
        run: dbt build --profiles-dir . --target prod